capital = {}
spitogatos = {}
tameio = {}
categories = {}
cat_spitogatos = {}
cat_capital = {}

capital["url"] = "http://realestate.capital.gr/properties/search-results/"
capital["unique_id"] = "//*[@id=\"df_field_xml_ref\"]/div[2]/text()"
capital["title"] = "//*[@id=\"area_listing\"]/h1/text()"
capital["price_num"] = "//*[@id=\"df_field_price\"]/span/text()"
capital["description"] = "//*[@id=\"df_field_additional_information\"]/div[2]/text()"
capital["region"] = "//*[@id=\"df_field_country_level1\"]/div[2]/text()"
capital["city"] = "//*[@id=\"df_field_country_level3\"]/div[2]/text()"
capital["neighborhood"] = "//*[@id=\"df_field_country_level4\"]/div[2]/text()"
capital["address"] = "//*[@id=\"df_field_address\"]/div[2]/text()"
capital["img_url"] = "//*[@id=\"media\"]/div[1]/img/@style"
capital["on_site_date"] = ""
capital["views_num"] = "//*[@id=\"area_listing\"]/section/ul[2]/li/span/text()"
capital["construction_year_num"] = "//*[@id=\"df_field_built_in\"]/div[2]/text()"
capital["category"] = "//*[@id=\"bread_crumbs\"]/ul/li[3]/a/text()"
capital["updated_date"] = ""
capital["last_update_num"] = ""
capital["debtor_name"] = ""
capital["auctioneer_name"] = ""
capital["auction_date"] = ""
capital["auction_number"] = ""
capital["property_area_num"] = "//*[@id=\"df_field_square_meters\"]/div[2]/text()"
capital["property_rooms_num"] = "//*[@id=\"df_field_bedrooms\"]/div[2]/text()"
capital["property_buy_or_rent"] = "//*[@id=\"df_field_propertyfor\"]/div[2]/text()"
capital["car_kms_num"] = ""
capital["car_cc_num"] = ""
capital["car_fuel"] = ""
capital["contact_legal_name"] = "//*[@id=\"main_container\"]/div[2]/div/aside/section[1]/div/ul/li[2]/text()"
capital["contact_name"] = "//*[@id=\"main_container\"]/div[2]/div/aside/section[1]/div/ul/li[1]/a/text()"
capital["contact_phone"] = "//*[@id=\"df_field_phone\"]/div[2]/text()"
capital["contact_mobile"] = ""
capital["contact_email"] = ""
capital["contact_website"] = "//*[@id=\"main_container\"]/div[2]/div/aside/section[1]/div/div/a/img/@style"


spitogatos["unique_id"] = ""
spitogatos["fulltext"] = "//*[@id=\"listingDetailsMainContent\"]/text()"
spitogatos["title"] = "//*[@id=\"main\"]/div/section[1]/div/div[1]/h1/text()"
spitogatos[
    "price_num"] = "//*[@id=\"carouselSideDetails\"]/div/div[2]/div[2]/h6/text()"
spitogatos[
    "description"] = "//*[@id=\"listingDetailsMainContent\"]/div[10]/div/text()"
spitogatos["city"] = "//*[@id=\"breadCrumbs\"]/a[2]/text()"
spitogatos["neighborhood"] = "//*[@id=\"breadCrumbs\"]/a[3]/text()"
spitogatos[
    "region"] = "//*[@id=\"carouselSideDetails\"]/div/div[1]/div[2]/h6/text()"
spitogatos["address"] = ""
spitogatos[
    "img_url"] = "//*[@id=\"listingDetailsMainContent\"]/div[1]/div[1]/div/@data-img"
spitogatos["on_site_date"] = ""
spitogatos["views_num"] = ""
spitogatos["construction_year"] = ""
spitogatos[
    "category_minor"] = "//*[@id=\"carouselSideDetails\"]/div/div[5]/div[2]/h6/text()"
spitogatos["updated_date"] = ""
spitogatos["last_update_num"] = ""
spitogatos["debtor_name"] = ""
spitogatos["auctioneer_name"] = ""
spitogatos["auction_date"] = ""
spitogatos["auction_number"] = ""
spitogatos[
    "property_area_num"] = "//*[@id=\"carouselSideDetails\"]/div/div[4]/div[2]/h6/text()"
spitogatos["property_rooms_num"] = ""
spitogatos["property_buy_or_rent"] = "//*[@id=\"breadCrumbs\"]/a[1]/text()"
spitogatos["car_kms_num"] = ""
spitogatos["car_cc_num"] = ""
spitogatos["car_fuel"] = ""
spitogatos["contact_legal_name"] = "//*[@id=\"listingDetailsSidebar\"]/div[1]/div[1]/div[2]/div[2]/a/text()"
spitogatos["contact_name"] = ""
spitogatos["contact_phone"] = "//*[@id=\"realtorInfoLinks\"]/div/span[2]/text()"
spitogatos["contact_mobile"] = "//*[@id=\"realtorInfoLinks\"]/div/span[4]/text()"
spitogatos["contact_email"] = ""
spitogatos[
    "contact_website"] = "//*[@id=\"listingDetailsSidebar\"]/div[1]/div[1]/div[1]/div/a/@href"


# tameio["url"] = "https://deltio.tnomik.gr"
tameio["unique_id"] = "//*[@id=\"guid\"]/text()"
tameio["title"] = "//*[@id=\"guid\"]/text()"
tameio["price_num"] = "//*[@id=\"offer_price\"]/text()"
tameio["description"] = "//*[@id=\"guid\"]/text()"
tameio["region"] = "//*[@id=\"currentStatusField\"]/text()"
tameio["city"] = "//*[@id=\"select_court\"]/text()"
tameio["neighborhood"] = ""
tameio["address"] = ""
tameio["img_url"] = ""
tameio["on_site_date"] = "//*[@id=\"publishedDateField\"]/text()"
tameio["views_num"] = ""
tameio["construction_year"] = ""
tameio["category_major"] = "//*[@id=\"select_asset_type\"]/text()"
tameio["category_minor"] = ""
tameio["updated_date"] = ""
tameio["last_update_num"] = ""
tameio["debtor_name"] = "//*[@id=\"debtor_name\"]/text()"
tameio["auctioneer_name"] = "//*[@id=\"auctioneer\"]/text()"
tameio["auction_date"] = "//*[@id=\"dateTextField\"]/text()"
tameio["auction_number"] = "//*[@id=\"related_auction\"]/text()"
tameio["property_area_num"] = ""
tameio["property_rooms_num"] = ""
tameio["property_buy_or_rent"] = ""
tameio["car_kms_num"] = ""
tameio["car_cc_num"] = ""
tameio["car_fuel"] = ""
tameio["contact_legal_name"] = ""
tameio["contact_name"] = ""
tameio["contact_phone"] = ""
tameio["contact_mobile"] = ""
tameio["contact_email"] = ""
tameio["contact_website"] = ""


# Category naming
categories['major_re_1'] = "residential"
categories['major_re_2'] = "commercial"
categories['major_re_3'] = "land"
categories['status_1'] = "sale"
categories['status_2'] = "rent"
categories['minor_re_si_1'] = "apartment"
categories['minor_re_si_2'] = "studio"
categories['minor_re_si_3'] = "detached"
categories['minor_re_si_3'] = "villa"
categories['minor_re_si_4'] = "detached"
categories['minor_re_si_5'] = "semi-detached"
categories['minor_re_co_1'] = "office"
categories['minor_re_co_2'] = "store"
categories['minor_re_co_3'] = "industrial"
categories['minor_re_co_4'] = "building"
categories['minor_re_co_5'] = "hotel"
categories['minor_re_co_6'] = "event hall"


# Category mapping for spitogatos
cat_spitogatos['major_re_1'] = "residential"
cat_spitogatos['major_re_2'] = "commercial"
cat_spitogatos['major_re_3'] = "land"
cat_spitogatos['status_1'] = "Sales"
cat_spitogatos['status_2'] = "Rent"
cat_spitogatos['minor_re_si_1'] = ""
cat_spitogatos['minor_re_si_2'] = ""
cat_spitogatos['minor_re_si_3'] = ""
cat_spitogatos['minor_re_si_3'] = ""
cat_spitogatos['minor_re_si_4'] = ""
cat_spitogatos['minor_re_si_5'] = ""
cat_spitogatos['minor_re_co_1'] = ""
cat_spitogatos['minor_re_co_2'] = ""
cat_spitogatos['minor_re_co_3'] = ""
cat_spitogatos['minor_re_co_4'] = ""
cat_spitogatos['minor_re_co_5'] = ""
cat_spitogatos['minor_re_co_6'] = ""

# Category mapping for capital real estate
cat_capital['major_re_1'] = ""
cat_capital['major_re_2'] = ""
cat_capital['major_re_3'] = ""
cat_capital['status_1'] = ""
cat_capital['status_2'] = ""
cat_capital['minor_re_si_1'] = ""
cat_capital['minor_re_si_2'] = ""
cat_capital['minor_re_si_3'] = ""
cat_capital['minor_re_si_3'] = ""
cat_capital['minor_re_si_4'] = ""
cat_capital['minor_re_si_5'] = ""
cat_capital['minor_re_co_1'] = ""
cat_capital['minor_re_co_2'] = ""
cat_capital['minor_re_co_3'] = ""
cat_capital['minor_re_co_4'] = ""
cat_capital['minor_re_co_5'] = ""
cat_capital['minor_re_co_6'] = ""
